{
 "title": "SRE App Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "SLO Compliance (Availability Last 24h)",
   "type": "stat",
   "description": "Porcentaje de tiempo que la aplicación estuvo disponible durante las últimas 24 horas.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(up{job=\"orders-app\"}[30d]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Order Creation Time",
   "type": "gauge",
   "description": "Mide el tiempo promedio que tarda en procesarse una orden",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ordersapp_order_creation_time_seconds_sum\r\n/\r\nordersapp_order_creation_time_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration per Endpoint (Avg Latency)",
   "type": "bargauge",
   "description": "Muestra la latencia promedio por endpoint",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum[5m])) by (uri)\r\n/\r\nsum(rate(http_server_requests_seconds_count[5m])) by (uri)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Orders created (last 1h)",
   "type": "timeseries",
   "description": "Muestra cuántas órdenes se crearon durante la última hora",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "increase(ordersapp_orders_total[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Status",
   "type": "stat",
   "description": "Muestra si el microservicio orders-app está siendo scrapeado correctamente por Prometheus.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"orders-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Product Sales Distribution",
   "type": "piechart",
   "description": "Porcentaje de cada producto en las ventas totales del sistema.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ordersapp_product_sold_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total orders created",
   "type": "stat",
   "description": "Muestra la cantidad total de órdenes creadas por la aplicación desde que fue iniciada.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ordersapp_orders_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Error Trend (Last 24h)",
   "type": "timeseries",
   "description": "Tendencia de errores recientes en la creación de órdenes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "increase(ordersapp_orders_failed_total[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Orders",
   "type": "stat",
   "description": "Número actual de órdenes activas almacenadas por el servicio.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ordersapp_active_orders", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Error Trend (Last 24h)",
   "type": "stat",
   "description": "Tendencia de errores recientes en la creación de órdenes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(ordersapp_orders_failed_total[24h])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}